from __future__ import annotations

from datetime import datetime, timedelta

from sqlalchemy import desc, func, select
from sqlalchemy.orm import Session

from opencost.models.models import OptimizerRecommendation, RoutingConfigVersion, UsageEvent
from opencost.optimizer.engine import STRATEGIES, generate_recommendations


def _period_days(period: str) -> int:
    return 7 if period == "7d" else 30


def get_cost_summary(db: Session, period: str = "7d") -> dict:
    days = _period_days(period)
    start = datetime.utcnow() - timedelta(days=days)
    row = db.execute(
        select(
            func.coalesce(func.sum(UsageEvent.estimated_cost_usd), 0.0),
            func.coalesce(func.sum(UsageEvent.total_tokens), 0),
            func.count(UsageEvent.id),
        ).where(UsageEvent.timestamp >= start)
    ).one()
    return {
        "period": period,
        "total_cost_usd": float(row[0] or 0.0),
        "total_tokens": int(row[1] or 0),
        "total_events": int(row[2] or 0),
    }


def get_usage_breakdown(db: Session, group_by: str, period: str = "30d") -> list[dict]:
    days = _period_days(period)
    start = datetime.utcnow() - timedelta(days=days)
    if group_by == "category":
        field = UsageEvent.task_category
    elif group_by == "provider":
        field = UsageEvent.provider
    else:
        field = UsageEvent.model

    stmt = (
        select(
            field,
            func.count(UsageEvent.id),
            func.coalesce(func.sum(UsageEvent.total_tokens), 0),
            func.coalesce(func.sum(UsageEvent.estimated_cost_usd), 0.0),
        )
        .where(UsageEvent.timestamp >= start)
        .group_by(field)
        .order_by(desc(func.count(UsageEvent.id)))
    )
    return [
        {"key": str(r[0] or "unknown"), "count": int(r[1]), "total_tokens": int(r[2]), "total_cost_usd": float(r[3])}
        for r in db.execute(stmt)
    ]


def get_recommendations(db: Session, strategy: str | None = None):
    stmt = select(OptimizerRecommendation).order_by(desc(OptimizerRecommendation.created_at))
    if strategy and strategy in STRATEGIES:
        stmt = stmt.where(OptimizerRecommendation.strategy_name == strategy)
    return list(db.scalars(stmt.limit(20)))


def simulate_config(db: Session, config: dict, period: str = "30d") -> dict:
    summary = get_cost_summary(db, period)
    strategy = config.get("defaults", {}).get("strategy", "balanced")
    factor = STRATEGIES.get(strategy, STRATEGIES["balanced"])["factor"]
    projected = summary["total_cost_usd"] * factor
    return {
        "period": period,
        "baseline_cost_usd": summary["total_cost_usd"],
        "projected_cost_usd": round(projected, 2),
        "estimated_savings_usd": round(summary["total_cost_usd"] - projected, 2),
    }


def export_config(db: Session, version_id: int) -> dict:
    rec = db.get(RoutingConfigVersion, version_id)
    if not rec:
        raise ValueError("Config version not found")
    return rec.config_payload_json


def save_config_from_recommendation(db: Session, rec: OptimizerRecommendation) -> RoutingConfigVersion:
    cfg = RoutingConfigVersion(
        created_at=datetime.utcnow(),
        version_name=f"{rec.strategy_name}-{rec.created_at.date()}",
        strategy_name=rec.strategy_name,
        description=rec.summary_markdown,
        config_payload_json=rec.config_payload_json,
        projected_monthly_cost_usd=rec.projected_monthly_cost_usd,
        notes="Generated by optimizer",
    )
    db.add(cfg)
    db.commit()
    db.refresh(cfg)
    return cfg


def generate_and_fetch(db: Session):
    recs = generate_recommendations(db)
    for rec in recs:
        save_config_from_recommendation(db, rec)
    return recs
